<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jarvis.AI\Jarvis.AI.csproj" />
    <ProjectReference Include="..\Jarvis.Audio\Jarvis.Audio.csproj" />
    <ProjectReference Include="..\Jarvis.Core\Jarvis.Core.csproj" />
    <ProjectReference Include="..\Jarvis.Persistence\Jarvis.Persistence.csproj" />
    <ProjectReference Include="..\Jarvis.Tools.Developer\Jarvis.Tools.Developer.csproj" />
    <ProjectReference Include="..\Jarvis.Tools.Windows\Jarvis.Tools.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>
